# Generated by Django 5.1 on 2024-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CalismaSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
                ('baslangic_saati', models.TimeField(blank=True, null=True)),
                ('bitis_saati', models.TimeField(blank=True, null=True)),
                ('ogle_arasi_baslangic', models.TimeField(blank=True, null=True)),
                ('ogle_arasi_bitis', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('konu', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('ad', models.CharField(default=None, max_length=30)),
                ('soyad', models.CharField(default=None, max_length=20)),
                ('telefon', models.CharField(default=None, max_length=11, primary_key=True, serialize=False)),
                ('e_posta', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('tarih', models.DateTimeField()),
                ('saat', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='service_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(default='#', max_length=100)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('content_en', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='explanation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='explanation',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
