# Generated by Django 5.1 on 2024-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0002_menu_doctorinfo_phone_explanation_hangiresim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='/home', max_length=100),
        ),
    ]
