# Generated by Django 5.1 on 2024-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0002_about_calismasaati_contact_randevu_servicepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='description_en',
            field=models.TextField(blank=True, default=models.TextField(blank=True, null=True), null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
