# Generated by Django 5.1 on 2024-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0003_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
