# Generated by Django 5.1 on 2024-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0003_servicepage_description_en_servicepage_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='basvuru_sebebi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
