# Generated by Django 5.1 on 2024-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0004_randevu_basvuru_sebebi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='caption',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='about',
            name='caption_en',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
