# Generated by Django 5.1 on 2024-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0005_remove_explanation_hangiresim_explanation_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
