# Generated by Django 5.1 on 2024-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0006_about_alter_sliderimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(default='/home', max_length=100)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
