# Generated by Django 5.1 on 2024-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0007_submenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submenu',
        ),
        migrations.AddField(
            model_name='menu',
            name='submenucontent',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='submenuname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='submenuurl',
            field=models.CharField(default='/home', max_length=100),
        ),
    ]
