# Generated by Django 5.1 on 2024-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0008_delete_submenu_menu_submenucontent_menu_submenuname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('url', models.CharField(default='#', max_length=100)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='submenuurl',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
