# Generated by Django 5.1 on 2024-08-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0009_services_alter_menu_submenuurl_alter_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
