# Generated by Django 4.1.3 on 2024-08-25 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0010_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalismaSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(max_length=10)),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('ogle_arasi_baslangic', models.TimeField()),
                ('ogle_arasi_bitis', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('e_posta', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('doktor', models.CharField(max_length=100)),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Klinik_Website.hasta')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
