# Generated by Django 5.1 on 2024-08-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0011_calismasaati_hasta_randevu_delete_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calismasaati',
            name='baslangic_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calismasaati',
            name='bitis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calismasaati',
            name='ogle_arasi_baslangic',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calismasaati',
            name='ogle_arasi_bitis',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
