# Generated by Django 5.1 on 2024-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0012_alter_calismasaati_baslangic_saati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='id',
        ),
        migrations.AddField(
            model_name='randevu',
            name='ad',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='randevu',
            name='e_posta',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='randevu',
            name='soyad',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='randevu',
            name='telefon',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Hasta',
        ),
    ]
