# Generated by Django 5.1 on 2024-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0013_remove_randevu_hasta_remove_randevu_id_randevu_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='tarih',
            field=models.DateTimeField(),
        ),
    ]
