# Generated by Django 5.1 on 2024-08-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0014_alter_randevu_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='doktor',
        ),
    ]
