# Generated by Django 5.1 on 2024-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0015_remove_randevu_doktor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosyalMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
            ],
        ),
    ]
