# Generated by Django 5.1 on 2024-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0016_sosyalmedya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosyalmedya',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sosyalmedya',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
