# Generated by Django 5.1 on 2024-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0018_alter_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
