# Generated by Django 5.1 on 2024-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0019_explanation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('konu', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
