# Generated by Django 5.1 on 2024-08-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klinik_Website', '0020_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
